[versions]
#AGP
agp = "7.1.3"
#Gradle
gradle = "7.1.2"
#Kotlin
kotlin = "1.6.21"
#Legacy support
legacySupport = "1.0.0"
#Coroutines
coroutines = "1.6.0"
#UI Components
material = "1.5.0"
constraint = "2.1.3"
viewBindingPropertyDelegate = "1.5.6"
appCompat = "1.4.1"
splashScreen = "1.0.0-beta01"
#Core
core = "1.7.0"
#Activity
activity = "1.4.0"
#fragment
fragment = "1.4.1"
#Lifecycle
lifecycle = "2.4.1"
#Navigation
navigation = "2.4.1"
#Hilt
hilt = "2.41"
#Retrofit
retrofit = "2.9.0"
#OkHttp
okHttp = "5.0.0-alpha.5"
#Room
room = "2.4.2"
#Paging
paging = "3.1.1"
#Firebase
firebase = "4.3.10"
firebasePlatform = "29.2.0"
#Glide
glide = "4.13.0"
#Koin
koin = "3.2.0-beta-1"
[libraries]

#Kotlin
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

#Core
android-core = { module = "androidx.core:core-ktx", version.ref = "core" }

#Fragment
fragment-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }

#Activity
activity-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }

#UI Components
ui-material = { module = "com.google.android.material:material", version.ref = "material" }
ui-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
ui-constraint = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint" }
ui-viewBindingPropertyDelegate = { module = "com.github.kirich1409:viewbindingpropertydelegate-noreflection", version.ref = "viewBindingPropertyDelegate" }
ui-splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }

#Legacy Support
legacySupport-legacySupport = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupport" }

#Lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }

#Navigation
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

#Hilt
hilt-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

#Retrofit
retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

#OkHttp

okHttp-okHttp = { module = "com.squareup.okhttp3:okhttp" }
okHttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okHttp" }
okHttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

#Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-kotlinExtensionsAndCoroutinesSupport = { module = "androidx.room:room-ktx", version.ref = "room" }

#Paging
paging-paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

#Glide
glide-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

#Firebase
firebase-platform = { module = "com.google.firebase:firebase-bom", version.ref = "firebasePlatform" }

#Koin
koin-koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }

[bundles]
#UI Components
uiComponents = ["ui-appCompat", "ui-constraint", "ui-material", "ui-viewBindingPropertyDelegate"]

#Room
roomBundle = ["room-runtime", "room-kotlinExtensionsAndCoroutinesSupport"]

#Retrofit
retrofitBundle = ["retrofit-retrofit", "retrofit-gsonConverter"]
#OkHttp
okHttpBundle = ["okHttp-bom", "okHttp-loggingInterceptor", "okHttp-okHttp"]

#Navigation
navigationBundle = ["navigation-fragment", "navigation-ui"]

#Lifecycle
lifecycleBundle = ["lifecycle-viewModel", "lifecycle-runtime", "lifecycle-liveData"]


[plugins]
#AGP
agp-library = { id = "com.android.library", version.ref = "agp" }
agp-applicationGradle = { id = "com.android.application", version.ref = "agp" }

#Kotlin
kotlin-gradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

#Navigation
navigation-safeArgsGradle = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
navigation-safeArgsPlug = { id = "androidx.navigation.safeargs.kotlin" }

#Hilt
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }